# If you change this file, please restart the server process.
gems:
  - octopress-autoprefixer
  - jekyll-redirect-from
port: 4001
title: Trigger Blog
email: support@triggerapp.com
description: > # this means to ignore newlines until "baseurl:"
  Trigger Blog
baseurl: ''
url: 'http://blog.triggerapp.com'
twitter_username: triggerapp
markdown: kramdown
permalink: /:year/:month/:title/
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'deploy']
